# Generated by Django 5.0.6 on 2024-07-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Catalogos/'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
